# Generated by Django 5.1 on 2024-08-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
