# Generated by Django 5.1 on 2024-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_product_current_rating_product_power_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
