# Generated by Django 5.1 on 2024-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
