# Generated by Django 5.1 on 2024-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_remove_product_image_url_product_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_rating',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_rating',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
